name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
        
jobs:

  build_docker_Jetson:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      id: prep
      run: |
        IMAGE="ghcr.io/mmeendez7/deploy_jetson"
        DOCKERFILE="docker/Dockerfile"

        echo ::set-output name=tag_latest::${IMAGE}:latest
        echo ::set-output name=dockerfile::${DOCKERFILE}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
    - name: Print available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        install: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Show builder instance name
      run: echo ${{ steps.buildx.outputs.name }}
    - name: Show available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build production image
      uses: docker/build-push-action@master
      with:
        platforms: linux/arm64/v8
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ${{ steps.prep.outputs.dockerfile }}
        push: true
        tags: |
          ${{ steps.prep.outputs.tag_latest }}

